### ISSUE TITLE
Complex json event - syntax error

### ISSUE THREAD

**Issue by aniecki** [awslabs/aws-sam-local#103]
Testing lambda by the call:
 $ _sam local invoke -e sns_event_struct0.json HelloWorld_

returns:

2017/08/31 19:58:47 Successfully parsed template.yaml
2017/08/31 19:58:47 Connected to Docker 
2017/08/31 19:58:47 Fetching lambci/lambda:nodejs6.10 image for nodejs6.10 runtime...
nodejs6.10: Pulling from lambci/lambda
Digest: sha256:b9a57b98dcfe226cac3fb0b8329594eefb62ba7089fa27cf8ac968e5736cc04a
Status: Image is up to date for lambci/lambda:nodejs6.10
2017/08/31 19:58:48 Invoking index.handler (nodejs6.10)
START RequestId: b33ec217-b676-12cc-d536-101d1233ef7a Version: $LATEST
Unable to parse input as json: Unexpected token 
 in JSON at position 503: SyntaxError
 in JSON at position 503
    at Object.parse (native)
END RequestId: b33ec217-b676-12cc-d536-101d1233ef7a
REPORT RequestId: b33ec217-b676-12cc-d536-101d1233ef7a	Duration: 10.13 ms	Billed Duration: 0 ms	Memory Size: 0 MB	Max Memory Used: 28 MB	

The beginning of the even file:
{ "Records": [
 { "EventSource": "aws:sns",
   "EventVersion": "1.0",
   "EventSubscriptionArn": "arn:aws:sns:eu-west-1:916174725480:new-fmi-opendata-rcrhirlam-surface-grib:b290c21a-2c65-48d6-b4bd-a7fd09f3fc0a",
   "Sns": {
          "Type": "Notification",
          "MessageId": "8d6d28db-33dc-52f6-9521-7adc18cf7536",
          "TopicArn": "arn:aws:sns:eu-west-1:916174725480:new-fmi-opendata-rcrhirlam-surface-grib",
          "Subject": "Amazon S3 Notification",
          "Message": "{\"Records\":
                  [{\"eventVersion\":\"2.0\",

The problem could be that it is json, inside json, as after the Message variable there is the Records one followed by colon which seems to be the problem.. ( counted to be at 503 line buffer)

How to fix it? 

The even.json seems to be a legitimate output as generated by a lambda triggered by an sns event.

**Comment by mhart** [comment]
@aniecki that doesn't look like valid JSON towards the end there:

> "Message": "{"Records":

Looks like there's an extra quote – should it be `"Message": {"Records":`?

**Comment by mhart** [comment]
Or it's possible that `Message` is supposed to be a string, in which case all quotes inside it need to be escaped:

```
"Message": "{\"Records\": ... "
```

**Comment by aniecki** [comment]
Yes, the json event as reported is just beginning of the whole file (for the sake of space clarity), and yes it is escaped, though the escape characters are somehow deleted by the github editor. 

One more thing, when validated by freeformatter.com it gives:
_The JSON input is NOT valid according to RFC 4627 (JSON specification). Unexpected character ( ) at position 503._

Then again, such json even is caught by a lambda function (sns trigger) thus I assume that it should also be processed by sam service?

**Comment by aniecki** [comment]
Supplied is the screenshot of the event json file..

![screenshot from 2017-09-03 12-54-19](https://user-images.githubusercontent.com/12697970/30002338-2b0e517c-90a7-11e7-9894-32b5486acb06.png)

**Comment by mhart** [comment]
@aniecki is that a newline in the middle of a string? (on line 10, 11, 12, etc)

They should also be escaped as `\n`

It looks to me like it should be:

```
"Message": "{\"Records\":\n[{\"eventVersion\":\"2.0\",\n\"eventSource\":\"aws:s3\",\n ...
```

**Comment by aniecki** [comment]
Thanks for that info, Indeed I have modified the string to be user friendly, didn't know that this new line can spoil the event. 

I will check and update later.

**Comment by aniecki** [comment]
Ok, this event  is now good in sam service,

Yet when validating by  freeformatter.com, it comes as (see below)

How to validate such event to be ok for sam invoke?

![screenshot from 2017-09-04 19-52-04](https://user-images.githubusercontent.com/12697970/30035477-dd792cac-91aa-11e7-86f0-1994a42ee0c8.png)

**Comment by aniecki** [comment]
Issue fixed, even when there is no info on the validator..
