### ISSUE TITLE
Decompressing into runtime container fails or freezes occasionally

### ISSUE THREAD

**Issue by igorakkerman** [awslabs/aws-sam-local#111]
I'm trying to use SAM Local on WIndows 10 to test my Lambda function, written in Java 8:
`sam local invoke --template sam.yaml --event event.txt`

The outcome is unpredictable, with three variations:
1. Request succeeds
2. Request freezes at 'Decompressing into runtime container'
3. Request fails with a bunch of Go errors at 'Decompressing into runtime container'

I attached the three respective logs:
[invoke-working.txt](https://github.com/awslabs/aws-sam-local/files/1286102/invoke-working.txt)
[invoke-frozen.txt](https://github.com/awslabs/aws-sam-local/files/1286103/invoke-frozen.txt)
[invoke-error.txt](https://github.com/awslabs/aws-sam-local/files/1286101/invoke-error.txt)

**Comment by PaulMaddox** [comment]
This looks like a potential bug in github.com/microsoft/go-winio 

https://github.com/Microsoft/go-winio/issues/41

I will investigate further tomorrow.
