### ISSUE TITLE
 Decompressing shaded.jar into runtime container fails with AppData\Local\Temp\aws-sam-local-1504877795714063500\license: The system cannot find the path specified.

### ISSUE THREAD

**Issue by syadama** [awslabs/aws-sam-local#114]
I'm trying test SAM Local on my Windows 10 machine with docker and the application is written in Java 8:

Here is how I am invoking it sam local invoke esignature-orch -e event.json and i am getting the below error.

sam local invoke esignature-orch -e event.json
2017/09/08 11:30:20 Successfully parsed template.yml
2017/09/08 11:30:20 Connected to Docker 1.30
2017/09/08 11:30:20 Fetching lambci/lambda:java8 image for java8 runtime...
java8: Pulling from lambci/lambda
Digest: sha256:7c7de2243109afc521e5414bb71a0b674a6c42019d5d2c92b6a4c88a17de1270
Status: Image is up to date for lambci/lambda:java8
2017/09/08 11:30:21 Invoking esign.orch.outbound.sm.processor.lambda.EsignOutboundProcessorLambda (java8)
2017/09/08 11:30:21 Decompressing esignature-orch-0.0.1-SNAPSHOT-shaded.jar into runtime container...
2017/09/08 11:30:48 mkdir C:\Users\*******\AppData\Local\Temp\aws-sam-local-1504884621593650800\license: The system cannot find the path specified.

**Comment by sanathkr** [comment]
Can you try with latest release - v0.2.2? I believe this is fixed there
