### ISSUE TITLE
Incorrect Usage: flag provided but not defined: -docker-network

### ISSUE THREAD

**Issue by rickypotato** [awslabs/aws-sam-local#116]
I tried to use `--docker-network <network-id>` to connect to docker network when I use sam local to invoke my lambda function locally. but it said `Incorrect Usage: flag provided but not defined: -docker-network`. it seems that `--docker-network` is not a valid OPTION.

when I type `sam local invoke -h`, I see these options:

USAGE:
   sam local invoke [command options] <function-identifier>

OPTIONS:
   --template value, -t value               AWS SAM template file (default: "template.[yaml|yml]") [$SAM_TEMPLATE_FILE]
   --log-file value, -l value               Optional. Logfile to send runtime logs to
   --env-vars value, -n value               Optional. JSON file containing values for Lambda function's environment variables.
   --event value, -e value                  JSON file containing event data passed to the Lambda function during invoke
   --debug-port value, -d value             Optional. When specified, Lambda function container will start in debug mode and will expose this port on localhost. [$SAM_DEBUG_PORT]
   --docker-volume-basedir value, -v value  Optional. Specifies the location basedir where the SAM file exists. If the Docker is running on a remote machine, you must mount the path where the SAM file exists on the docker machine and modify this value to match the remote machine. [$SAM_DOCKER_VOLUME_BASEDIR]

Could anyone please help me on this?
Thanks!

**Comment by PaulMaddox** [comment]
Hi @rickypotato, this feature has been added to our development branch, but has not yet been released to NPM.

You can either install SAM Local via the Go instructions on the README, or wait until our next release to NPM (shouldn't be long).
