### ISSUE TITLE
 Unsupported run time

### ISSUE THREAD

**Issue by patelhr** [awslabs/aws-sam-local#118]
template.yaml:
AWSTemplateFormatVersion : '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: A hello world application.
Resources:
  Hello:
    Type: AWS::Serverless::Function
    Properties:
      Handler: Handler.cs
      Runtime: dotnetcore1.0

Hello Help needed,
While running "sam validate" it gives "Valid" output but when I am trying to run "sam local invoke" it throws me below error
**"Could not initiate dotnetcore1.0 runtime: unsupported runtime"**

**Comment by PaulMaddox** [comment]
SAM Local does not currently support the .NET Core runtime.
It's something we'd like to support in the future, but don't have any timeline for.
