### ISSUE TITLE
dynamo db as trigger 

### ISSUE THREAD

**Issue by mrigankt** [awslabs/aws-sam-local#119]
i am trying to use dynamo db as my trigger for lambda function.
 aws dynamodb describe-table --table-name BarkTable
"LatestStreamArn": "arn:aws:dynamodb:ddblocal:000000000000:table/BarkTable/stream/2017-09-01T08:52:49.560"
 My template.yml

AWSTemplateFormatVersion : '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Description: dynamodb
Resources:
  dynamodb:
    Type: AWS::Serverless::Function
    Properties:
      Timeout: 60
      Runtime: nodejs6.10
      Handler: index.handle
      Events:
        Input:
           Type: DynamoDB
           Properties:
                Stream: arn:aws:dynamodb:ddblocal:000000000000:table/BarkTable/stream/2017-09-01T08:52:49.560
                StartingPosition: TRIM_HORIZON
                BatchSize: 10

But getting error 
**2017/09/12 00:35:41 Failed to parse template: invalid YAML template: yaml: line 12: found character that cannot start any token**

**Comment by PaulMaddox** [comment]
Hi @mrigankt. 

I can't tell for sure as the template has lost it's formatting/indentation, however this is likely caused by using tabs (`\t`) instead of spaces in your template. YAML does not allow tabs, and must use spaces. 

Feel free to re-open this issue if that's not the cause.

Thanks
