### ISSUE TITLE
cannot populate body tag in event with ajax curl will

### ISSUE THREAD

**Issue by Liamdelee** [awslabs/aws-sam-local#136]
I am running sam local pritty great with a dynamodb local aswel now today i am working on getting the ajax calls for my webpage ready and after some time i got the get one going but the post is more of a challenge, is there a way to populate the body tag inside of the event? with this curl i can:
**curl -d {id:8} http://127.0.0.1:3000/resource**
but with ajax it just won't get inside of the body tag.
any ideas why or how i can fix this?

Many thanks

**Comment by sanathkr** [comment]
I am a bit confused. Body tag == HTTP response body? If so yes, in your Lambda function response you set body property in the JSON to be whatever your response body should be. 

what exact error are you getting with Ajax call?

**Comment by Liamdelee** [comment]
`{ httpMethod: 'POST',
  **body: ''**,
  resource: '/resource',
  requestContext:
   { resourceId: '',
     apiId: '',
     resourcePath: '/resource',
     httpMethod: '',
     requestId: '',
     accountId: '',
     identity:
      { apiKey: '',
        userArn: '',
        cognitoAuthenticationType: '',
        caller: '',
        userAgent: '',
        user: '',
        cognitoIdentityPoolId: '',
        cognitoIdentityId: '',
        cognitoAuthenticationProvider: '',
        sourceIp: '127.0.0.1:56561',
        accountId: '' } },
  queryStringParameters: {},
  headers:
   { Accept: '*/*',
     'Accept-Encoding': 'gzip, deflate, br',
     'Accept-Language': 'nl-NL,nl;q=0.8,en-US;q=0.6,en;q=0.4',
     Connection: 'keep-alive',
     'Content-Length': '0',
     Origin: 'http://evil.com/',
     'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.91 Safari/537.36' },
  pathParameters: {},
  stageVariables: null,
  path: '/resource' }`

this highlited body tag needs to be populated so i can use it in my lambda function right? but as you can see it is just empty nothing in it except ''. with a CURL i can get it to fill in the body tagg but it is not a JSON so i can't parse it or use it in my lambda so now i try with a ajax call but everytime i try it is just plain empty as seen above.

many thanks already for your response

**Comment by sanathkr** [comment]
If body is populated with Curl, then this is not a bug in SAM Local. Did you check Network tab in Chrome's Inspector whether the network from your browser is passing body? If not there is some bug upstream

**Comment by Liamdelee** [comment]
when i tested my project friday i did get to a post but i wanted to test today to see if i idd can see it get put true with the browser but now i get a **Failed to load http://127.0.0.1:3000/resource: Response for preflight has invalid HTTP status code 404** never had this before did something change with an update in the security or something? if i just type in the curl it works fine so i guesse it has something todo with my security but i can't really figure out what because it worked just fine friday.

**Comment by Liamdelee** [comment]
i found out the problem was that i had:
`contentType: "application/json; charset=utf-8",`
and
` dataType: "json",`
in my ajax call removed those and everything works fine. srry for taking up your time

**Comment by sanathkr** [comment]
Glad you found the issue
