### ISSUE TITLE
Clarification request: upgrade instructions

### ISSUE THREAD

**Issue by cvuijst** [awslabs/aws-sam-local#138]
Due to the new version available, execution of sam-local results in:

> A newer version of the AWS SAM CLI is available!
> Your version:   0.2.0
> Latest version: 0.2.2
> See https://github.com/awslabs/aws-sam-local for upgrade instructions

It is unclear which upgrade instructions are referenced at the provided link.

**Comment by Liamdelee** [comment]
you just need to use **npm install -g aws-sam-local** again and it will take care of everything (uninstall reinstall the 0.2.2 version) for you. (atleast that is what i did and worked out great) maybe there is also the **npm upgrade -g aws-sam-local** but not sure if this will be working but the first one works great for me

**Comment by cvuijst** [comment]
I did the "**nam install**" - Worked!
Thanks for the response

-- Charles

**Comment by sanathkr** [comment]
Fair enough. We will make the messaging clear
