### ISSUE TITLE
In the generated API event, not all HTTP methods are replaced

### ISSUE THREAD

**Issue by bottemav** [awslabs/aws-sam-local#142]
If you generate an API event while specifying the HTTP method (e.g. GET), the generated event still contains a httpMethod attribute with value POST. The HTTP method is only replaced once.
`sam local generate-event api --method GET`
The generated event:
```
{
  "body": "{ \"test\": \"body\"}",
  "resource": "/{proxy+}",
  "requestContext": {
    "resourceId": "123456",
    "apiId": "1234567890",
    "resourcePath": "/{proxy+}",
    "httpMethod": "GET",
...
  "httpMethod": "POST",
  "stageVariables": {
    "baz": "qux"
  },
  "path": "/examplepath"
}
```

**Comment by sanathkr** [comment]
That's a bug. Can you send a quick PR replacing this word here with `{{.Method}}` - https://github.com/awslabs/aws-sam-local/blob/develop/generate-event.go#L349? I can get it merged
