### ISSUE TITLE
Question: dotnet core support timeline

### ISSUE THREAD

**Issue by olingern** [awslabs/aws-sam-local#144]
I see in the documentation that it's planned, but not currently supported. 

Is this feature planned for delivery in 2017?

**Comment by PaulMaddox** [comment]
It's unlikely that we will have this in place for 2017, unless somebody wants to contribute it via a pull request to the https://github.com/lambci/docker-lambda project.

**Comment by jason-riddle** [comment]
Update: See https://github.com/awslabs/aws-sam-local/pull/311 for dotnet core 2.0 support.
