### ISSUE TITLE
Support for Lambda integration

### ISSUE THREAD

**Issue by corneliusuciu** [awslabs/aws-sam-local#16]
The README mentions `aws-sam-local` uses Lambda proxy integration by default.  Is there a way to tell `aws-sam-local` to use Lambda integration instead?

**Comment by sanathkr** [comment]
No, SAM defaults to proxy integration when you define the APIs. We are keeping the behavior consistent here with SAM Local.

**Comment by corneliusuciu** [comment]
I switched to lambda proxy integration.  Lambda integration not really needed.

**Comment by alexiaallanic-myob** [comment]
With SAM, it is possible to define your Api configuration using AWS::Serverless::Api. When you then define x-amazon-apigateway-integration, you can choose to have type "aws" or "aws_proxy". Shouldn't this "aws" type option be supported by sam-local? Then it would make sense to support lambda integration.

**Comment by dgoradia** [comment]
I agree with @alexiaallanic-myob lambda integration should also be supported.

**Comment by red8888** [comment]
Will this never be supported? If not that means I can _only_ use the proxy integration with SAM. 

Otherwise whats the point if I can't test locally the same as the deployed version?
