### ISSUE TITLE
Shutting down sam local start-api correctly

### ISSUE THREAD

**Issue by uruloke** [awslabs/aws-sam-local#161]
When I close sam local start-api I get the following when trying to start it afterwards.
`listen tcp 127.0.0.1:3000: bind: address already in use`

**Comment by PaulMaddox** [comment]
How are you closing it? A `Ctrl+C` will exit the process, and free up any ports used.

Can you do a `ps aux | grep sam` to check what is actually running.

**Comment by uruloke** [comment]
I am closing it with `Ctrl+C`
![image](https://user-images.githubusercontent.com/5870441/31229913-8a92032e-a9e2-11e7-9948-8d75cc89be73.png)
the one with `-p 3001`, is actually running.

**Comment by PaulMaddox** [comment]
I can't replicate this issue. Did this just happen the once, or is it consistently every time?

**Comment by Liamdelee** [comment]
Not sure but can you try and use command+c?

**Comment by uruloke** [comment]
Just tried on another Mac and some problem. Yes it is consistent, it happens every time.

@Liamdelee, command+c does nothing, or did you want me to copy something for you?

**Comment by joshuadfranklin** [comment]
What Mac and Docker version are you using? The "bind: address already in use" was a common Docker problem with older versions.
Ctrl-C works fine for me on this:
```
sw_vers ; docker --version
ProductName:	Mac OS X
ProductVersion:	10.12.6
BuildVersion:	16G29
Docker version 17.09.0-ce, build afdb6d4
```

**Comment by uruloke** [comment]
This is my specs

```
ProductName:	Mac OS X
ProductVersion:	10.12.6
BuildVersion:	16G29
Docker version 17.09.0-ce, build afdb6d4
```
Running same version as you.

**Comment by uruloke** [comment]
nvm, reinstalling docker somehow fixed it. It works now, somehow my docker installation was corrupt I guess.

**Comment by warren-vodafone** [comment]
I'm troubleshooting running sam on a corporate network. So I need to start it, test it, and stop it. A lot.

I was looking for a sam local --shutdown - but ended up with kill

staying in the foreground and blocking around the tty is cumbersome
