### ISSUE TITLE
Support for AWS::Lambda::Function and AWS::ApiGateway::RestApi

### ISSUE THREAD

**Issue by corneliusuciu** [awslabs/aws-sam-local#18]
When running `aws-sam-local` with a template file that uses `AWS::Lambda::Function` and `AWS::ApiGateway::RestApi` I see that `aws-sam-local` complains about missing Serverless functions and related API events.  Can `aws-sam-local` work with `AWS::Lambda::Function` and `AWS::ApiGateway::RestApi` ?

**Comment by sanathkr** [comment]
No, it works specifically with SAM resources - AWS::Serverless::Api/Function. We could expand in future to support other resources too, but that would require us to support creating API proxy by reading the Swagger file.

Do you use inline Swagger or external Swagger?

**Comment by corneliusuciu** [comment]
I'm using inline Swagger

**Comment by corneliusuciu** [comment]
Will there be support for inline Swagger with AWS::Serverless::Api in the near future?

**Comment by PaulMaddox** [comment]
We're looking to add it, but don't have a timeline for it yet.

We need to complete some work on the CloudFormation/SAM parser that we use first, then work on swagger support will be starting.

**Comment by bittib** [comment]
+1 for requesting this feature. I followed AWS Lambda tutorial to create my first lambda service and then got stuck with using sam local to test it because of this issue.

**Comment by corneliusuciu** [comment]
Is there an update on the timeline for adding support for inline Swagger with AWS::Serverless::Api?

**Comment by SAPessi** [comment]
We've just merged #222 that adds support for Swagger as part of the Serverless Api resource.

**Comment by PaulMaddox** [comment]
Just bundled up v0.2.3 and released it to NPM.
You can upgrade with `npm update -g aws-sam-local`.
