### ISSUE TITLE
Running SAM Local with Java on Windows

### ISSUE THREAD

**Issue by Petrax** [awslabs/aws-sam-local#183]
I am trying to run the Java sample project on sam local under Windows. I have added CodeUri property to the template YAML to make the JAR file visible for SAM.
> CodeUri: target/HelloWorld-1.0.jar

Docker Toolbox is installed and invoking a particular function fetches lambda docker image.

> 2017/10/27 08:42:08 Successfully parsed template.yml
←[34mINFO←[0m[0000] Unable to use system certificate pool: crypto/x509: system root pool is not available on Windows
> 2017/10/27 08:42:08 Connected to Docker 1.33
←[34mINFO←[0m[0000] Unable to use system certificate pool: crypto/x509: system root pool is not available on Windows
> 2017/10/27 08:42:08 Fetching lambci/lambda:java8 image for java8 runtime...
java8: Pulling from lambci/lambda
Digest: sha256:5e1f24ebf98bf010e94e8eb7d3eeec3d24d2a7d97a458756dda27134de526aa2
Status: Image is up to date for lambci/lambda:java8

However invoking the function itself causes error:
> 2017/10/27 08:39:18 Reading invoke payload from stdin (you can also pass it from file with --event)
> 2017/10/27 08:39:18 Invoking com.aws.codestar.projecttemplates.handler.HelloWorldHandler (java8)
> 2017/10/27 08:39:18 Decompressing C:\Users\dzielins\git\P18-Bool\target\HelloWorld-1.0.jar
>2017/10/27 08:39:18 Could not invoke function: Error response from daemon: invalid volume specification: 'C:\Users\dzielins\AppData\Local\Temp\aws-sam-local-1509086358382936700:/var/task:ro'

As I have read in some other posts and README file, this might be caused by incorrect setting of Docker volume basedir. So I tried using both `--docker-volume-basedir` switch and environment variable `SAM_DOCKER_VOLUME_BASEDIR` by setting them to `/c/Users/dzielins/git/P18-Bool` as advised. This did not help in any way, as now the error that occurs is:

> 2017/10/27 08:41:01 Reading invoke payload from stdin (you can also pass it from file with --event)
> 2017/10/27 08:41:01 Invoking com.aws.codestar.projecttemplates.handler.HelloWorldHandler (java8)
←[32mSTART RequestId: 1d73caa9-7554-485d-8eaf-81de3a712d3a Version: $LATEST←[0m
←[31mjava.lang.ClassNotFoundException: com.aws.codestar.projecttemplates.handler.HelloWorldHandler
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:348)

What should be done in order to make SAM Local and Docker instance see and invoke the built JAR file in correct way?

**Comment by Petrax** [comment]
After some investigation I was able to identify the cause. If the deployed artifact is a JAR file, then before running SAM local it is automatically extracted to a temp location (by default to `C:\Users\<username>\AppData\Local\Temp\aws-sam-local-<some_number>`). This location is then retrieved as current working directory from the OS and combined with `:/var/task:ro`.  This forms an invalid path that cannot be recognized on the Docker container resulting in an error.

Setting the path manually by using `--docker-volume-basedir` switch or environment variable `SAM_DOCKER_VOLUME_BASEDIR` is not very convenient as with each run the built JAR gets copied to a different temp location.

**Comment by choro0626** [comment]
I still have the same error

`
$ sam local invoke HelloWorld -e event.json
2017/10/30 23:31:05 Successfully parsed template.yaml
[34mINFO[0m[0000] Unable to use system certificate pool: crypto/x509: system r
oot pool is not available on Windows
2017/10/30 23:31:05 Connected to Docker 1.33
[34mINFO[0m[0000] Unable to use system certificate pool: crypto/x509: system r
oot pool is not available on Windows
2017/10/30 23:31:05 Fetching lambci/lambda:nodejs4.3 image for nodejs4.3 runtime
...
nodejs4.3: Pulling from lambci/lambda
Digest: sha256:45851b3c08683a09f4e6cf6b9a91af1059ea71e300be425dcb38ab93aa4bb50e
Status: Image is up to date for lambci/lambda:nodejs4.3
2017/10/30 23:31:08 Invoking index.handler (nodejs4.3)
2017/10/30 23:31:08 Could not invoke function: Error response from daemon: inval
id volume specification: 'C:/Users/Person1:/var/task:ro'
`

tried ` --docker-volume-basedir  \C\Users\Person1`

`
2017/10/30 23:36:49 Invoking index.handler (nodejs4.3)
[32mSTART RequestId: a57f9167-1ec9-1f7f-dc86-1de27befd57a Version: $LATEST[0m
[31mUnable to import module 'index': Error[0m
[31m    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)[0m

{"errorMessage":"Cannot find module '/var/task/index'","errorType":"Error","stac
kTrace":["Function.Module._load (module.js:276:25)","Module.require (module.js:3
53:17)","require (internal/module.js:12:17)"]}
[32mEND RequestId: a57f9167-1ec9-1f7f-dc86-1de27befd57a[0m
[32mREPORT RequestId: a57f9167-1ec9-1f7f-dc86-1de27befd57a     Duration: 8.57 m
s       Billed Duration: 0 ms   Memory Size: 0 MB       Max Memory Used: 24 MB
[0m
`

How did you solve it?
It would be great and I am glad  if you tell me.

**Comment by PaulMaddox** [comment]
Fix incoming soon!

**Comment by mvpmurali** [comment]
Yes same issue is existing for me in windows 7. Expecting the fix soon. Thanks

**Comment by ksrinath** [comment]
PaulMaddox, approx when is fix expected to be released?

**Comment by PaulMaddox** [comment]
Sorry @ksrinath, the last month has been super busy at AWS with the run up to re:Invent. This is still waiting on code review, but I know @sanathkr has been super busy working on some super cool new Serverless stuff for re:Invent, which has taken priority.

**Comment by joshuaeilers** [comment]
+1

**Comment by khadir-syed** [comment]
+1

**Comment by sdaclin** [comment]
+1

**Comment by gruau** [comment]
+1
