### ISSUE TITLE
Don't break on first line

### ISSUE THREAD

**Issue by pjarts** [awslabs/aws-sam-local#198]
When running `sam local start-api` with the `--debug-port` option set it seems to always break on the first line of code. Every time I want to test a request to the API I have to send it, tab to VS code, start the debugger and press continue (F5) before it will process my request. To avoid having to run two instances of the api, or restarting it every time you want to switch between debug/no debug I think it would be more convenient to only break on breakpoints, or at least make it optional to break on first line.

**Comment by PaulMaddox** [comment]
Unfortunately this is something controlled by Visual Studio Code / the NodeJS debugger, and is outside the control of this project. All SAM Local is doing is running the NodeJS runtime with the debug flags set, and exposing the port to your host/IDE.
