### ISSUE TITLE
Attempting to install under Ubuntu (BASH) for Windows 10 errors

### ISSUE THREAD

**Issue by jensenmo** [awslabs/aws-sam-local#199]
I'm running Windows 10 version 1709 (OS build 16299.64) and I'm getting the error below when attempting to install aws-sam-local with npm in Ubuntu Bash:

$ sudo npm install -g aws-sam-local
loadDep:uuid → cache add 
...

> aws-sam-local@0.2.2 postinstall /usr/local/lib/node_modules/aws-sam-local
> go-npm install

Downloading from URL: https://github.com/awslabs/aws-sam-local/releases/download/v0.2.2/sam_0.2.2_linux_amd64.tar.gz
fs.js:681
  return binding.rename(pathModule._makeLong(oldPath),
                 ^

Error: EACCES: permission denied, rename 'bin/sam' -> '/usr/local/bin/sam'
    at Error (native)
    at Object.fs.renameSync (fs.js:681:18)
    at /usr/local/lib/node_modules/aws-sam-local/node_modules/go-npm/bin/index.js:62:12
    at /usr/local/lib/node_modules/aws-sam-local/node_modules/go-npm/bin/index.js:51:9
    at ChildProcess.exithandler (child_process.js:204:7)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:821:16)
    at Socket.<anonymous> (internal/child_process.js:319:11)
    at emitOne (events.js:77:13)
npm ERR! Linux 4.4.0-43-Microsoft
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "-g" "aws-sam-local"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE

npm ERR! aws-sam-local@0.2.2 postinstall: `go-npm install`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the aws-sam-local@0.2.2 postinstall script 'go-npm install'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the aws-sam-local package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     go-npm install
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs aws-sam-local
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls aws-sam-local
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/mjensen/npm-debug.log

**Comment by timjrobinson** [comment]
I'm also getting the same issue installing both locally and globally on RHEL. 

```
$ node --version
v8.9.1
$ npm --version
5.5.1
```

**Comment by PaulMaddox** [comment]
You should not need to use sudo to install (and it may have caused some permission problems if you  initially tried with sudo, as it creates directories that are root-owned).

Please see the instructions on this page of the NPM documentation to fix your npm permissions: 
https://docs.npmjs.com/getting-started/fixing-npm-permissions.

**Comment by minfrin** [comment]
I get the same error on ubuntu 16.04, this time without sudo:

    npm ERR! Linux 4.4.0-1013-aws
    npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "-g" "aws-sam-local"
    npm ERR! node v4.2.6
    npm ERR! npm  v3.5.2
    npm ERR! path /usr/local/lib
    npm ERR! code EACCES
    npm ERR! errno -13
    npm ERR! syscall access

    npm ERR! Error: EACCES: permission denied, access '/usr/local/lib'
    npm ERR!     at Error (native)
    npm ERR!  { [Error: EACCES: permission denied, access '/usr/local/lib']
    npm ERR!   errno: -13,
    npm ERR!   code: 'EACCES',
    npm ERR!   syscall: 'access',
    npm ERR!   path: '/usr/local/lib' }
    npm ERR! 
    npm ERR! Please try running this command again as root/Administrator.

The error is accurate - there is no expectation of any non-root write access to /usr/local/lib.

npm tells me to run this as root, while @PaulMaddox says "You should not need to use sudo to install".

Which of these two is correct?
