### ISSUE TITLE
npm does not work any more after failed installation attempt of aws-sam-local

### ISSUE THREAD

**Issue by realharry** [awslabs/aws-sam-local#205]
I tried to install it on my Ubuntu workstation (`sudo npm i -g aws-sam-local`), and it failed with EACCES error. 

The README page points to the NPM documentation, whose remedies are questionable (in my view). I decided not to install `aws-sam-local`. But, since then, I cannot use `npm` for my local projects any more. I keep getting "Error: EACCES: permission denied" errors. It seems like the failed installation attempt changed ownership of certain npm directories.

It's very likely an `aws-sam-local` issue (rather than an npm issue).

**Comment by jebberjeb** [comment]
@realharry I had the same issue on an Ubuntu EC2 instance.  I installed the package from Releases and that's worked for me so far.

```
wget https://github.com/awslabs/aws-sam-local/releases/download/v0.2.2/sam_0.2.2_linux_amd64.deb
sudo dpkg -i ./sam_0.2.2_linux_amd64.deb
```

**Comment by realharry** [comment]
@jebberjeb Thanks for the info. I successfully installed the deb package. Thanks!

**Comment by iph** [comment]
`sudo npm i -g aws-sam-local` are you supposed to use sudo with npm -g? sudo will elevate you to superuser, and install recursively installs files. The combination would mean that any shared packages installed would be owned by superuser, and not your actual user -- essentially locking you out of those packages.

**Comment by PaulMaddox** [comment]
@iph is correct - you should not use sudo and it should install just fine without it.

**Comment by realharry** [comment]
@PaulMaddox @iph I disagree. What does "-g" mean? In the shared system (like Unix/Linux), global installation should be done by a user with elevated privilege. @PaulMaddox "you should not use sudo and it should install just fine without it." I think you are completely mistaken. If you can do "npm i -g" on your system without sudo, your system is broken.
