### ISSUE TITLE
goformation repo missing?

### ISSUE THREAD

**Issue by gaurish** [awslabs/aws-sam-local#24]
this repo is mentioned here: https://github.com/awslabs/aws-sam-local/blob/develop/validate.go#L7

but i can't find it
```
> curl -I https://github.com/awslabs/goformation
HTTP/1.1 404 Not Found
Date: Sat, 12 Aug 2017 18:39:08 GMT
Content-Type: text/plain; charset=utf-8
Server: GitHub.com
Status: 404 Not Found
```

**Comment by PaulMaddox** [comment]
Hi @gaurish, we'll be open sourcing this library soon. For now, you can find the source in the vendor/ directory.
