### ISSUE TITLE
Validation fails on !Join

### ISSUE THREAD

**Issue by dipthegeezer** [awslabs/aws-sam-local#25]
Hi

I have a SAM template that works fine when I deploy via the AWS cli using aws cloudformation package and deploy. However it fails via sam. I get the following validation error.

> 2017/08/12 21:08:31 0.1.0
2017/08/12 21:08:31 ERROR:  did not find expected ',' or ']' (line: 7; col: 0)

The line in question has a !Join. Like the following:

> AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: CRUD service
Outputs:
  ApiUrl:
    Description: URL of API endpoint
    Value: !Join ['', ['https://', !Ref "MyApi", '.execute-api.', !Ref 'AWS::Region', '.amazonaws.com/Prod']]

I've omitted the remainder of the template for brevity.

**Comment by heitorlessa** [comment]
Out of curiosity, have you tried with !Sub format instead of Join?

And also, do you receive the same error when using the long function name
"Fn::Join"?

**Comment by sanathkr** [comment]
I have a hunch what might be going on. Will take a detailed look once I get in front of the computer.

Is it failing on "sam local" calls or or on "sam validate" call?

**Comment by sanathkr** [comment]
Just pushed a PR that fixes this bug. Since this blocks all `sam local` commands, we will release a new version once this PR gets approved. Hang tight!

**Comment by dipthegeezer** [comment]
Cool, thanks for the quick turnaround!
