### ISSUE TITLE
Installing 404 with new 0.2.5 version

### ISSUE THREAD

**Issue by elison-chen** [awslabs/aws-sam-local#267]
I tried `npm install -g aws-sam-local` and I am seeing a 404 error. 

Error Message:
```
> aws-sam-local@0.2.5 postinstall /usr/local/lib/node_modules/aws-sam-local
> go-npm install

Downloading from URL: https://github.com/awslabs/aws-sam-local/releases/download/v0.2.5/sam_0.2.5_darwin_amd64.tar.gz
Error downloading binary. HTTP Status Code: 404
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! aws-sam-local@0.2.5 postinstall: `go-npm install`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the aws-sam-local@0.2.5 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

```

Looks like it is having an issue finding the newest version 0.2.5 that was just released an hour ago.

For now I have just ran `npm install -g aws-sam-local@0.2.4` to download 0.2.4. Just wanted to bring this up incase anyone else runs into this issue.

**Comment by PaulMaddox** [comment]
Yes - we found an issue with the Go support added in v0.2.5, so have moved the release back to draft status until we solve it.
