### ISSUE TITLE
fork/exec /var/task/main: permission denied

### ISSUE THREAD

**Issue by terrywarwar** [awslabs/aws-sam-local#274]
I successfully deployed a golang lambda api service using `sam package` and `sam deploy`.

And when I test the lambda function, I get the error below.
`{
  "errorMessage": "fork/exec /var/task/main: permission denied",
  "errorType": "PathError"
}`

**Comment by PaulMaddox** [comment]
Do you have a built binary called main in your directory when you run the package command?

Are you using Linux/Mac or Windows? The built binary needs to have execute permissions.

**Comment by terrywarwar** [comment]
Yes, built using `GOOS=linux go build -o main` on a Mac
`-rwxr-xr-x   1 terry  staff  8087634 24 Jan 14:37 main`

**Comment by terrywarwar** [comment]
I downloaded the file that was packaged to S3 and it has different permission.
`-rw-r--r--@ 1 terry  staff  8087634 24 Jan 16:55 main`

**Comment by sanathkr** [comment]
Here is a nifty little tool to zip up properly: https://github.com/aws/aws-lambda-go#for-developers-on-windows

**Comment by terrywarwar** [comment]
When I set the `CodeUri: main` the packaged file has permissions as `-rw-r--r--@` but when I set the `CodeUri: .` to the code directory, the binary has the correct permission when packaged `-rwxr-xr-x@ `

**Comment by neoadventist** [comment]
Hey @terrywarwar @PaulMaddox I have a similar situation but I get: 
```
{
  "errorMessage": "fork/exec /var/task/main: no such file or directory",
  "errorType": "PathError"
}
```

when I run `sam local start-api --template sam.yml`

Handler is set to `main` 

I think my problem is similar, but I hope to get to the permission problem :)

**Comment by terrywarwar** [comment]
@neoadventist have you done a build using `GOOS=linux go build -o main`?

**Comment by neoadventist** [comment]
@terrywarwar yes

**Comment by terrywarwar** [comment]
I had the same issue using `aws cloudformation`, I wonder if this causing the issue when `CodeUri` is set to a file instead of a directory.
https://github.com/aws/aws-cli/blob/e354da887af26c3a4546026e743f10bbf851eecb/awscli/customizations/cloudformation/artifact_exporter.py#L212

`shutil.copyfile` doesn't copy the meta-data.

**Comment by eggsbenjamin** [comment]
Not sure if this is the case here, but I found this issues page while debugging so thought I'd post here to help others debugging the `fork/exec /var/task/main permission denied` issue.

I had a similar issue and the issue was that I'd neglected to create a main function and my go package name wasn't main.

```
package main

import (
  "github.com/aws/aws-lambda-go/lambda"
)

func main() {
  lambda.Start(MyHandler)
}
```

**Comment by terrywarwar** [comment]
Created PR, https://github.com/aws/aws-cli/pull/3112

**Comment by charger88** [comment]
@neoadventist, did you find solution for your problem? I have the same issue.

**Comment by neoadventist** [comment]
@charger88 nah, still the same issue. My code seem to work okay on my mac vs the linux/WSL environment, so i'm using that. (plus the whole lambda experiment was put on hold for now) please be sure to comment here when you've solved it!

**Comment by charger88** [comment]
@neoadventist I've just forgot about building step.
Run this (replace $1 to your actual filename without extension):
GOOS=linux go build -o $1 $1.go

**Comment by josephmcasey** [comment]
It seems like this issue persists due to file permissions and the missing argument specified by @charger88.

`GOOS=linux go build -o main main.go`
as opposed to
`GOOS=linux go build -o main`

and Read, Write, Execute permissions instead of simply Read or Write permissions.

**Comment by jkrnak** [comment]
If anyone got here seeing the same error @neoadventist had
```
{
  "errorMessage": "fork/exec /var/task/main: no such file or directory",
  "errorType": "PathError"
}
```
Also make sure that your are building on glibc if you are using os, runtime or net. 
Lambdas are executing with glibc runtime. 
This could be relevant if you were building on alpine for example, which has musl instead of glibc.
This case you can also try to link your libs statically instead of dynamically.

This worked for me to build on alpine and run on aws.
(your musl-gcc might be in a different location) 
```
CC=/usr/bin/x86_64-alpine-linux-musl-gcc GOOS=linux go build -x -ldflags '-linkmode external -extldflags "-static"' -a -tags netgo -installsuffix netgo -o main main.go
```

**Comment by rayhaanq** [comment]
what was the actual fix for this? I'm using windows and running this:
```
set GOOS=linux
set GOARCH=amd64
go build -ldflags="-s -w -v" -o bin/hello hello/main.go
go build -ldflags="-s -w -v" -o bin/world world/main.go
```

**Comment by mikeatlas** [comment]
Just leaving this here for anyone who happens to stumble across this:

My zip file had some of my full build path in it from my Makefile. I needed to add `-j` switch to `zip` to flatten out the file paths:

```make
build:
	${GOBUILD} -ldflags="-d -s -w" -o ${BINPATH}/hello ./cmd/hello/main.go
	chmod +x ${BINPATH}/hello
	zip -j ${BINPATH}/hello.zip ${BINPATH}/hello
```

This works when the Lambda handler is specified as `hello`.

**Comment by Shockem** [comment]
@mikeatlas That worked for me! I just added the `-j` flag to zip for junking the file path.

**Comment by zzerjae** [comment]
If you are still having this problem, see my case

```
.
# permission denied
├── bin
│   └── main
└── template
    └── template.yaml
```

```
.
# It works fine.
├── bin
│   └── main
└── template
    └── template.yaml
```

**Comment by maddinek** [comment]
> Just leaving this here for anyone who happens to stumble across this:
> 
> My zip file had some of my full build path in it from my Makefile. I needed to add `-j` switch to `zip` to flatten out the file path inside the archive:
> 
> ```makefile
> build:
> 	${GOBUILD} -ldflags="-d -s -w" -o ${BINPATH}/hello ./cmd/hello/main.go
> 	chmod +x ${BINPATH}/hello
> 	zip -j ${BINPATH}/hello.zip ${BINPATH}/hello
> ```
> 
> This works when the Lambda handler is specified as `hello`.
for me it was literally just the...
> zip -j
thanks mate!

**Comment by rajendragosavi** [comment]
@maddinek , Where did you add this ?  I am using AWS SAM hello-world application and getting. {"errorType":"exitError","errorMessage":"RequestId: 09bda008-f1ba-1f08-63cd-c9df843425e3 Error: fork/exec /var/task/hello-world: permission denied"}  .

Any idea on this .

**Comment by rajendragosavi** [comment]
@jkrnak . Hey. I am also facing same issue. I did not understand what did you said.

**Comment by rajendragosavi** [comment]
@EdisonGonzalez , Hey , Even I am facing the permission denied issue. 
**{"errorType":"exitError","errorMessage":"RequestId: c7306307-98aa-1690-1fe1-1e411b065441 Error: fork/exec /var/task/hello-world: permission denied"}**. When I execute - sam local invoke HelloWorldFunction --no-event

**Comment by brnlee** [comment]
> > build:
> > ${GOBUILD} -ldflags="-d -s -w" -o ${BINPATH}/hello ./cmd/hello/main.go
> > chmod +x ${BINPATH}/hello
> > zip -j ${BINPATH}/hello.zip ${BINPATH}/hello
> 
> for me it was literally just the...
> 
> > zip -j
> 
> thanks mate!

I am able to create the zip and upload manually through the AWS console to get the Lambda function working. However, how would one do this using sam package + sam deploy?
