### ISSUE TITLE
Invalid environment override file env.json

### ISSUE THREAD

**Issue by zachschultz** [awslabs/aws-sam-local#278]
I have a working Node lambda function that I can execute with SAM Local, but I am trying to include environment variables now. When trying to invoke my function like so: `echo '{"msg":"hi"}' | sam local invoke "MyFunc" --env-vars env.json` I am getting the error:

```
Invalid environment override file env.json: json: cannot unmarshal string into Go value of type map[string]string
```

The function still executes fine, I just don't have any variables from my `env.json` available. My JSON file looks like this: 

```
{
  "dbPort": "3306",
  "dbHost": "docker.for.mac.localhost",
  "dbPass": "MYPASS",
  "dbName": "MYDBNAME"
}
```

Nothing out of the ordinary and everything is a string. I'm not sure what's going on.

**Comment by rvypandey** [comment]
I just had the issue, and fixed it by adding one more child, like
{
  "New_Child": {
    "dbPort": "3306",
    "dbHost": "docker.for.mac.localhost",
    "dbPass": "MYPASS",
    "dbName": "MYDBNAME"
   }
}

I figured this by going through readme: https://github.com/awslabs/aws-sam-local#environment-variable-file
AND
some code: https://github.com/awslabs/aws-sam-local/blob/4bfe1b84779d0f47c6803ef64c8495cc62d26c5a/env.go#L101

**Comment by zachschultz** [comment]
Ah thanks! Looks good and works fine.

**Comment by heitorlessa** [comment]
hey Zach and Ravi thanks for sharing that - I just hit this issue when working on something new.
