### ISSUE TITLE
Environment variable override file not working for `sam local start-api`

### ISSUE THREAD

**Issue by PaulMaddox** [awslabs/aws-sam-local#28]
Passing environment variables via `--env-vars file.json` doesn't work with `sam local start-api`.

It looks like it's using the Function.FunctionName rather than the SAM/CloudFormation logical ID:
https://github.com/awslabs/aws-sam-local/blob/develop/start.go#L112

Fix incoming...

**Comment by caspian154** [comment]
I'm observing this behavior again with version 0.6.0. It was working with version 0.2.11, but when I upgraded per the nagging instructions I can't get any environment vars to work in sam local again.
