### ISSUE TITLE
Async code outside handler is not executed

### ISSUE THREAD

**Issue by Kivol** [awslabs/aws-sam-local#280]
Hello,

The `setTimeout` part of the code below is not executed when the function is invoked. Moreover, the handler does not execute any code if I put any asynchronous code outside the handler.

What I actually trying to do is to build a GraphQL server based on pre-generated MySQL connection pool, so the connection pool should be supplied in advance to execute the actual handler.

Is this a bug, or is there any way to avoid this type of structure?

```javascript
let flag = false;

setTimeout(() => {
	flag = true;
}, 500); // Some async task prior to actual execution

exports.handler = (evt, ctx, cb) => {
	while (!flag) {}
	cb(null, { statusCode: 200, body: 'HelloWorld' });
};
```

**Comment by morrighan** [comment]
```javascript
const EventEmitter = require('events');
let flag = new EventEmitter();

setTimeout(() => {
	flag.emit('fire');
}, 500); // Some async task prior to actual execution

exports.handler = (evt, ctx, cb) => {
	flag.on('fire', () => cb(null, { statusCode: 200, body: 'HelloWorld' }));
};
```

**Comment by Kivol** [comment]
@morrighan Thanks for the suggestion but it wouldn't work when the second time handler executes while the whole code warm-loaded once.

**Comment by morrighan** [comment]
hmmm... how about this?

```javascript
const flag = (() => {
    let resolve, reject;

    const promise = new Promise((...args) => {
        [ resolve, reject ] = args;
    });

    promise.resolve = resolve;
    promise.reject = reject;

    return promise;
})();

setTimeout(() => {
    flag.resolve({ statusCode: 200, body: 'HelloWorld' });
}, 500); // Some async task prior to actual execution

exports.handler = (event, context, callback) => {
    flag.then(result => {
        callback(null, result);
    }).catch(error => {
        callback(error);
    });
};
```

**Comment by Kivol** [comment]
The problem was not from the async task, but your suggestion looks neat. I've actually tried setting `context.callbackWaitsForEmptyEventLoop` variable before I saw your post and it works! Thank you very much.
