### ISSUE TITLE
Add support for Node 8.10

### ISSUE THREAD

**Issue by lmammino** [awslabs/aws-sam-local#343]
With this https://aws.amazon.com/blogs/compute/node-js-8-10-runtime-now-available-in-aws-lambda/ hitting the news, I hope SAM Local will update soon to support it :)

I'll be running a workshop in the next few weeks and it would be great to go fully on Node.js 8.10 🤓

**Comment by mhart** [comment]
docker-lambda now has support for Node.js 8.10 👍

**Comment by jaccus** [comment]
Got an ETA on released package?
