### ISSUE TITLE
Missing Makefile?

### ISSUE THREAD

**Issue by mhart** [awslabs/aws-sam-local#40]
`CONTRIBUTING.md` says:

> You may run all test by either running the `make test` target (requires `go`, and `go cover` to be installed).

But there's no `Makefile` so `make test` just exits with:

```
make: Nothing to be done for `test'.`
```

**Comment by sanathkr** [comment]
We don't use make files. That guide is wrong. Use `go get <url>` to pull the code, and `go test` to run tests. 

Can you send a PR fixing this?
