### ISSUE TITLE
Support for serving static files 

### ISSUE THREAD

**Issue by sanathkr** [awslabs/aws-sam-local#41]
If you are building a serverless website, Static files like Javascript, HTML or PNG are usually uploaded to S3 in a separate build step. This works when you are deploying and running code in Lambda. But when using SAM Local, you need these resources served by SAM Local CLI

Ex:
localhost:3000 -> serves the index.html
localhost:3000/myfile.js -> should serve Javascript
localhost:3000/static/image.png -> should serve images

Today, the only endpoint exposed via SAM Local are the APIs configured in your SAM file. This is not sufficient. We need to support serving static files from the directory where their Lambda function is mounted.

**Proposal:**
If a route is not found, before returning 404, have SAM Local check `pwd` or Lambda function's mount directory for static files matching the name/path. If found, return the file. Otherwise return 404. This will give you static file capabilities right out of the box, without any extra work. 

We can expose `--public-dir` parameter to specify path to search for static files.

**Comment by PaulMaddox** [comment]
Should be quick to add. 

https://github.com/gorilla/mux#static-files

**Comment by PaulMaddox** [comment]
I think it makes more sense to default the `public/` for the `--public-dir`.

Two reasons:

1) The AWS CodeStar Node.JS Serverless project uses `public/`, so this would work out of the box - great for new customers and demos.

2) I don't think there would be many instances of people wanting to serve up both their Serverless app (java/node.js source) as well as their static assets, so I don't think that matches what people would deploy to AWS in their Lambda deployment package.

Thoughts?

**Comment by sanathkr** [comment]
Agree with 1. 
Don't agree with 2. If I am building a serverless website, I need to serve static content. 

Can we call it `--static-dir` instead of `public-dir`? It makes the intent more clear. Also can we allow multiple `--static-dir`? Frameworks like expressjs allow this. If a file with same name exists in both places, the directory specified first will take precedence. All of them will mount at `/` of the HTTP listener.

**Comment by PaulMaddox** [comment]
Will make the param `--static-dir`, but I don't think the CLI framework we're using allows multiple, so will have to leave that for now.

PR incoming.

**Comment by sanathkr** [comment]
Sounds good.

**Comment by turjachaudhuri** [comment]
> Sounds good.

Hi Sanath , 
In serverless there are a few custom plugins which help you in uploading a set of files/folders to a s3 bucket as part of the serverless deploy step.
Is there any alternative like that ?
I want to avoid the step of uploading the files manually .
I want to simply create a bucket as part of my SAM template and then upload files from a specific folder in my local directory to the created bucket.
Is this possible?
