### ISSUE TITLE
[Question] - SyntaxError when using Python, boto3 and s3

### ISSUE THREAD

**Issue by maoo** [awslabs/aws-sam-local#59]
_Apologies in advance if this is not the right place to open this issue, I don't have an extensive experience with aws-sam-local or Python, so I may be missing something really stupid._

I have a problem with [my simple sam function](https://gist.github.com/maoo/2175a1c4b75a80c7271943591afb4920); assuming that `test.py` and `template.yaml` are in the current folder, the issue can be reproduced by simply running `echo '{}' | sam local invoke Test`.

The error I get is `SyntaxError: invalid syntax` on line `client = boto3.client('s3')` - full history on https://gist.github.com/maoo/2175a1c4b75a80c7271943591afb4920#file-error-log

The interesting part is that running the same function without `sam`, everything works; assuming that `test.py` and `template.yaml` are in the current folder, you can test the following command...
```
pip install boto3 -t .
python -c 'from test import test1; test1(None,None)'
```
... which expects to return an error saying `The specified key does not exist.`

**Comment by rafaharo** [comment]
Seems that your test scripts is not using standard spaces as separator (you have probably used the tab within a text editor and not a proper Python IDE). Not sure, but could be that taking quick a look at the raw file

**Comment by maoo** [comment]
Thanks @rafaharo , I've tried to use spaces across the test.py file, but got the same result; I suppose that - if it was an indentation issue - also the `python -c` command would fail.

**Comment by maoo** [comment]
Fixed the issue by using `python2.7` as `Runtime` in `template.yaml` (see https://gist.github.com/maoo/2175a1c4b75a80c7271943591afb4920#file-template-yaml-L10)

I'll close the issue here and post it to https://github.com/boto/boto3
