### ISSUE TITLE
Flag to disable pulling new Docker container and reuse cached container

### ISSUE THREAD

**Issue by sanathkr** [awslabs/aws-sam-local#67]
Currently SAM CLI pulls new Docker container every time you run. If no new Docker container version exists, it will use the cached container. Otherwise it will start downloading the container which can be slow when you have bad internet or lead to bad experience when you are demo-ing the tool.

Provide a flag to disable docker container version check and use the cached container.

**Comment by PaulMaddox** [comment]
This was implemented:
https://github.com/awslabs/aws-sam-local/pull/94
