### ISSUE TITLE
Package to local

### ISSUE THREAD

**Issue by httpstergeek** [awslabs/aws-sam-local#72]
It appears sam can only package to S3.  It would be nice if to package locally so we could leverage our existing CI process and tools for artifacts.

**Comment by sanathkr** [comment]
The only functionality done by package command is to upload your code to S3. Without that, the command is basically a no-op. 

What else do you want to achieve with package command?

**Comment by httpstergeek** [comment]
We have a build process which currently doesn't use S3.  It would be nice artifact (zip file) could be scp to the local machine running aws-sam or remote server.
