### ISSUE TITLE
No binary installed with yarn

### ISSUE THREAD

**Issue by mhart** [awslabs/aws-sam-local#87]
The yarn install succeeds, but there's no binary:
```
/ # yarn global add aws-sam-local
yarn global v0.27.5
warning package.json: No license field
warning No license field
[1/4] Resolving packages...
[2/4] Fetching packages...
warning fsevents@1.1.2: The platform "linux" is incompatible with this module.
info "fsevents@1.1.2" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
[4/4] Building fresh packages...
warning "aws-sam-local@0.2.0" has no binaries
warning No license field
Done in 8.92s.
/ # sam --version
/bin/sh: sam: not found
```

I believe it would be good to get working with yarn just because I've seen far fewer problems with global installs with yarn vs npm (especially npm@5 – it still has some teething problems)

**Comment by sanathkr** [comment]
NPM install is actually handled by this package https://github.com/sanathkr/go-npm. Unfortunately it calls `npm` to get the directory where binaries should be installed - https://github.com/sanathkr/go-npm/blob/master/src/index.js#L28-L50

I need to find if the execution is coming from Yarn and handle it differently.

**Comment by sanathkr** [comment]
Closing this in favor of https://github.com/sanathkr/go-npm/issues/1
