### ISSUE TITLE
can we also display the logging to stderr?

### ISSUE THREAD

**Issue by allinwonder** [awslabs/aws-sam-local#91]
I am using logging module in lambda functions. In production, these logs are written to stderr and they go to CloudWatch log. But when I use the `sam local invoke` to test, these logs are not able to be displayed in the shell.

Can we make the logs to stderr displayed in the local test as well?

**Comment by sanathkr** [comment]
stderr from the docker container is output to the CLI's stderr - https://github.com/awslabs/aws-sam-local/blob/develop/invoke.go#L158. Can you use the `--log-file` option and try? stderr from docker container should be output to the log file

**Comment by sanathkr** [comment]
Closing since it hasn't gotten traction

**Comment by bigunyak** [comment]
In SAM v0.4.0 log messages logged with `logging` module (python 3.6) are neither shown in the console nor printed in the log file with the `--log-file` option.
Looks like a regression, could you please reopen the issue?
Trivial code example is below.
```python
import logging

logging.basicConfig(level=logging.INFO, format='[%(asctime)s] [%(levelname)s] %(message)s')
log = logging.getLogger(__name__)

def handler(event, context):
    log.info("Received S3 event: " + json.dumps(event, indent=2))
    print("TESTTTTTTTTTTTTTTTTTT")
```
Print function works as expected.
