### ISSUE TITLE
exec: "aws": executable file not found in $PATH

### ISSUE THREAD

**Issue by djake** [awslabs/aws-sam-local#98]
When running `sam package` I get `exec: "aws": executable file not found in $PATH`.

```
$ command -v aws
/Users/<username>/Library/Python/3.6/bin/aws
```
Invoking aws directly seems to work as expected.
Globally installed on a Mac (with nvm).

Please let me know if you have any ideas or if I can provide additional information.

**Comment by PaulMaddox** [comment]
Hi @djake. I'm not sure what will be causing this, and can't replicate it on OSX here.

The code responsible is super simple, and just uses [Go's stdlib for executing binaries](https://golang.org/pkg/os/exec/#Command).

It should respect the $PATH on your system, and find the AWS command there.

See:
https://github.com/awslabs/aws-sam-local/blob/develop/package.go

**Comment by sanathkr** [comment]
Closing this because this has no repro. Please open if you are still blocked or need any help.

**Comment by kpapagno** [comment]
I had the exact same issue, with the same symptoms.  I was able to resolve by doing a pip uninstall awscli, then I did a brew update, then brew install awscli and the problem was resolved

**Comment by djake** [comment]
@kpapagno Thanks for posting that! And @PaulMaddox sorry for my lack of follow up...moved along to other things, but I thank you for the quick response.

**Comment by expertcoder** [comment]
I am having the same problem, I have detailed my problem here. https://stackoverflow.com/questions/49212796/unusual-installation-of-aws-cli

It might not even be an issue with sam, I will continue to look into this can get back to you

**Comment by abhimanyuNitSri** [comment]
> I had the exact same issue, with the same symptoms. I was able to resolve by doing a pip uninstall awscli, then I did a brew update, then brew install awscli and the problem was resolved

It worked for me just that I had to ` brew link --overwrite awscli` to link the awscli installed by the brew
